// Total products: 105

export interface PharmaProduct {
  name: string
  emoji: string
  category: 'injectable' | 'oral' | 'sarms' | 'peptides' | 'pct'
  origin: string
  tags: string[]
  variants: Array<{ label: string; price: number }>
  stock: number | null
}

export const PHARMA_PRODUCTS: PharmaProduct[] = [
  // --- INJECTABLE STEROIDS — Deus Medical ---
  {
    name: 'TESTOMED E 250',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 43 }],
    stock: null,
  },
  {
    name: '3-TRENBOMED 150',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 70 }],
    stock: null,
  },
  {
    name: 'DECAMED 250',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 56 }],
    stock: null,
  },
  {
    name: 'PRIMOMED 100',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 86 }],
    stock: null,
  },
  {
    name: 'TESTOMED C 250',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 43 }],
    stock: null,
  },
  {
    name: 'SUSTAMED 250',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 46 }],
    stock: null,
  },
  {
    name: 'MASTERMED E 200',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 68 }],
    stock: null,
  },
  {
    name: 'EQUIMED 250',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 52 }],
    stock: null,
  },
  {
    name: 'DHB-MED 100',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 68 }],
    stock: null,
  },
  {
    name: 'MASTERMED P 100',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 54 }],
    stock: null,
  },
  {
    name: 'DECAMED PP 100',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 42 }],
    stock: null,
  },
  {
    name: 'TESTOMED 100',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 38 }],
    stock: null,
  },
  {
    name: 'TESTOMED P 100',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 36 }],
    stock: null,
  },
  {
    name: 'WATERMED',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 14 }],
    stock: null,
  },
  {
    name: 'TRENBOMED E 200',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 68 }],
    stock: null,
  },
  {
    name: 'TRENBOMED A 100',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 61 }],
    stock: null,
  },
  {
    name: 'DIANAMED 100',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 49 }],
    stock: null,
  },
  {
    name: 'PARAMED 76.5',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 68 }],
    stock: null,
  },
  {
    name: 'TESTOMED U 250',
    emoji: '💉',
    category: 'injectable',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'injectable'],
    variants: [{ label: 'Unità', price: 41 }],
    stock: null,
  },

  // --- INJECTABLE STEROIDS — Astera Labs ---
  {
    name: 'TESTOSTERONE PROPIONATE',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 36 }],
    stock: null,
  },
  {
    name: 'TESTOSTERONE PHENYLPROPIONATE',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 36 }],
    stock: null,
  },
  {
    name: 'NANDROLONE PHENYLPROPIONATE NPP',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 42 }],
    stock: null,
  },
  {
    name: 'NANDROLONE DECANOATE',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 62 }],
    stock: null,
  },
  {
    name: 'SUSTANON 300MG',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 52 }],
    stock: null,
  },
  {
    name: 'SUSTANON 500MG',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 82 }],
    stock: null,
  },
  {
    name: 'BOLDENONE UNDECYLENATE',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 59 }],
    stock: null,
  },
  {
    name: 'METHENOLONE ENANTHATE 100',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 80 }],
    stock: null,
  },
  {
    name: 'METHENOLONE ENANTHATE 200',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 154 }],
    stock: null,
  },
  {
    name: 'TRENBOLONE ACETATE',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 61 }],
    stock: null,
  },
  {
    name: 'TRENBOLONE ENANTHATE',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 68 }],
    stock: null,
  },
  {
    name: 'STANOZOLOL injectable',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 44 }],
    stock: null,
  },
  {
    name: 'L-CARNITINE',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 20 }],
    stock: null,
  },
  {
    name: 'BACTERIOSTATIC WATER',
    emoji: '💉',
    category: 'injectable',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'injectable'],
    variants: [{ label: 'Unità', price: 14 }],
    stock: null,
  },

  // --- ORAL STEROIDS — Deus Medical ---
  {
    name: 'ANAVAMED 10',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 31 }],
    stock: null,
  },
  {
    name: 'DIANAMED 10',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 16 }],
    stock: null,
  },
  {
    name: 'ANADROMED 50',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 37 }],
    stock: null,
  },
  {
    name: 'WINIMED 10',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 19 }],
    stock: null,
  },
  {
    name: 'PROVIMED 25',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 31 }],
    stock: null,
  },
  {
    name: 'TURIMED 10',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 23 }],
    stock: null,
  },
  {
    name: 'HALOMED 5',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 62 }],
    stock: null,
  },
  {
    name: 'CABERMED 0.5',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 82 }],
    stock: null,
  },
  {
    name: 'PRIMOMED 25',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 103 }],
    stock: null,
  },
  {
    name: 'SUPERMED 10',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 56 }],
    stock: null,
  },
  {
    name: 'NEBIMED 5',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 21 }],
    stock: null,
  },
  {
    name: 'TELMIMED 40',
    emoji: '💊',
    category: 'oral',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'oral'],
    variants: [{ label: 'Unità', price: 27 }],
    stock: null,
  },

  // --- ORAL STEROIDS — Astera Labs ---
  {
    name: 'OXANDROLONE',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 122 }],
    stock: null,
  },
  {
    name: 'METHANDIENONE',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 62 }],
    stock: null,
  },
  {
    name: 'MESTEROLONE',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 82 }],
    stock: null,
  },
  {
    name: 'STANOZOLOL oral',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 68 }],
    stock: null,
  },
  {
    name: 'METHYLDROSTANOLONE SUPERDROL',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 56 }],
    stock: null,
  },
  {
    name: 'TURINABOL',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 89 }],
    stock: null,
  },
  {
    name: 'OXYMETHOLONE',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 41 }],
    stock: null,
  },
  {
    name: 'SIBUTRAMINE',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 68 }],
    stock: null,
  },
  {
    name: 'CABERGOLINE',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 109 }],
    stock: null,
  },
  {
    name: 'METHYL-1-TESTOSTERONE',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 41 }],
    stock: null,
  },
  {
    name: 'FLUOXYMESTERONE HALOTESTIN',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 62 }],
    stock: null,
  },
  {
    name: 'MIBOLERONE CHEQUE DROPS',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 82 }],
    stock: null,
  },
  {
    name: 'METHYLTRENBOLONE',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 62 }],
    stock: null,
  },
  {
    name: '17A-METHYLTESTOSTERONE',
    emoji: '💊',
    category: 'oral',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'oral'],
    variants: [{ label: 'Unità', price: 48 }],
    stock: 0,
  },

  // --- SARMs — Deus Medical ---
  {
    name: 'MK677 10',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'sarms'],
    variants: [{ label: 'Unità', price: 62 }],
    stock: null,
  },
  {
    name: 'GW501516 10',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'sarms'],
    variants: [{ label: 'Unità', price: 56 }],
    stock: null,
  },
  {
    name: 'MK2866 10',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'sarms'],
    variants: [{ label: 'Unità', price: 44 }],
    stock: null,
  },

  // --- SARMs — Astera Labs ---
  {
    name: 'MK677',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'sarms'],
    variants: [{ label: 'Unità', price: 48 }],
    stock: null,
  },
  {
    name: 'MK2866',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'sarms'],
    variants: [{ label: 'Unità', price: 37 }],
    stock: null,
  },
  {
    name: 'GW501516',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'sarms'],
    variants: [{ label: 'Unità', price: 43 }],
    stock: null,
  },

  // --- SARMs — Biaxol ---
  {
    name: 'YK11',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Biaxol',
    tags: ['biaxol', 'sarms'],
    variants: [{ label: 'Unità', price: 89 }],
    stock: null,
  },
  {
    name: 'ANDARINE S4',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Biaxol',
    tags: ['biaxol', 'sarms'],
    variants: [{ label: 'Unità', price: 74 }],
    stock: null,
  },
  {
    name: 'CARDARINE GW501516',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Biaxol',
    tags: ['biaxol', 'sarms'],
    variants: [{ label: 'Unità', price: 67 }],
    stock: null,
  },
  {
    name: 'IBUTAMOREN MK677',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Biaxol',
    tags: ['biaxol', 'sarms'],
    variants: [{ label: 'Unità', price: 74 }],
    stock: null,
  },
  {
    name: 'LIGANDROL LGD4033',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Biaxol',
    tags: ['biaxol', 'sarms'],
    variants: [{ label: 'Unità', price: 74 }],
    stock: null,
  },
  {
    name: 'OSTARINE MK2866',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Biaxol',
    tags: ['biaxol', 'sarms'],
    variants: [{ label: 'Unità', price: 74 }],
    stock: null,
  },
  {
    name: 'S23',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Biaxol',
    tags: ['biaxol', 'sarms'],
    variants: [{ label: 'Unità', price: 74 }],
    stock: null,
  },
  {
    name: 'STENABOLIC SR9009',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Biaxol',
    tags: ['biaxol', 'sarms'],
    variants: [{ label: 'Unità', price: 74 }],
    stock: null,
  },
  {
    name: 'TESTOLONE RAD140',
    emoji: '🧬',
    category: 'sarms',
    origin: 'Biaxol',
    tags: ['biaxol', 'sarms'],
    variants: [{ label: 'Unità', price: 82 }],
    stock: null,
  },

  // --- PEPTIDES & HGH — Deus Medical ---
  {
    name: 'DEUSTROPIN 4/12 HGH 120iu',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'peptides'],
    variants: [{ label: 'Unità', price: 258 }],
    stock: null,
  },
  {
    name: 'BPC-157',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'peptides'],
    variants: [{ label: 'Unità', price: 48 }],
    stock: null,
  },
  {
    name: 'HCG (Deus)',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'peptides'],
    variants: [{ label: 'Unità', price: 54 }],
    stock: null,
  },
  {
    name: 'SEMAGLUTIDE',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'peptides'],
    variants: [{ label: 'Unità', price: 136 }],
    stock: null,
  },
  {
    name: 'CJC-1295 DAC',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'peptides'],
    variants: [{ label: 'Unità', price: 41 }],
    stock: null,
  },
  {
    name: 'IPAMORELIN',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'peptides'],
    variants: [{ label: 'Unità', price: 27 }],
    stock: null,
  },
  {
    name: 'HGH FRAGMENT 176-191 (Deus)',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'peptides'],
    variants: [{ label: 'Unità', price: 54 }],
    stock: null,
  },
  {
    name: 'TB-500',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'peptides'],
    variants: [{ label: 'Unità', price: 41 }],
    stock: null,
  },
  {
    name: 'PT-141',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'peptides'],
    variants: [{ label: 'Unità', price: 41 }],
    stock: null,
  },
  {
    name: 'EPITHALON',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'peptides'],
    variants: [{ label: 'Unità', price: 41 }],
    stock: null,
  },

  // --- PEPTIDES & HGH — Astera Labs ---
  {
    name: 'HCG (Astera)',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'peptides'],
    variants: [{ label: 'Unità', price: 54 }],
    stock: null,
  },
  {
    name: 'TB500 & BPC157 combo',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'peptides'],
    variants: [{ label: 'Unità', price: 136 }],
    stock: null,
  },
  {
    name: 'MELANOTAN 2',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'peptides'],
    variants: [{ label: 'Unità', price: 41 }],
    stock: null,
  },
  {
    name: 'HGH FRAGMENT 176-191 (Astera)',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'peptides'],
    variants: [{ label: 'Unità', price: 95 }],
    stock: null,
  },
  {
    name: 'HGH',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'peptides'],
    variants: [{ label: 'Unità', price: 340 }],
    stock: 0,
  },

  // --- PEPTIDES & HGH — Biaxol ---
  {
    name: 'MELANOTAN II Nasal Spray',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Biaxol',
    tags: ['biaxol', 'peptides'],
    variants: [{ label: 'Unità', price: 59 }],
    stock: null,
  },
  {
    name: 'BPC-157 Capsules',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Biaxol',
    tags: ['biaxol', 'peptides'],
    variants: [{ label: 'Unità', price: 119 }],
    stock: 0,
  },
  {
    name: 'KPV Capsules',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Biaxol',
    tags: ['biaxol', 'peptides'],
    variants: [{ label: 'Unità', price: 148 }],
    stock: 0,
  },
  {
    name: 'GLP-1 BOOSTER Capsules',
    emoji: '🧪',
    category: 'peptides',
    origin: 'Biaxol',
    tags: ['biaxol', 'peptides'],
    variants: [{ label: 'Unità', price: 62 }],
    stock: 0,
  },

  // --- POST CYCLE THERAPY (PCT) — Deus Medical ---
  {
    name: 'CLOMIMED 50',
    emoji: '🔄',
    category: 'pct',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'pct'],
    variants: [{ label: 'Unità', price: 28 }],
    stock: null,
  },
  {
    name: 'ENCLOMIMED 25',
    emoji: '🔄',
    category: 'pct',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'pct'],
    variants: [{ label: 'Unità', price: 82 }],
    stock: null,
  },
  {
    name: 'ARIMIMED 1',
    emoji: '🔄',
    category: 'pct',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'pct'],
    variants: [{ label: 'Unità', price: 37 }],
    stock: null,
  },
  {
    name: 'AROMAMED 25',
    emoji: '🔄',
    category: 'pct',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'pct'],
    variants: [{ label: 'Unità', price: 41 }],
    stock: null,
  },
  {
    name: 'NOLVAMED 20',
    emoji: '🔄',
    category: 'pct',
    origin: 'Deus Medical',
    tags: ['deus-medical', 'pct'],
    variants: [{ label: 'Unità', price: 31 }],
    stock: null,
  },

  // --- POST CYCLE THERAPY (PCT) — Astera Labs ---
  {
    name: 'TAMOXIFEN CITRATE',
    emoji: '🔄',
    category: 'pct',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'pct'],
    variants: [{ label: 'Unità', price: 30 }],
    stock: null,
  },
  {
    name: 'ANASTROZOLE',
    emoji: '🔄',
    category: 'pct',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'pct'],
    variants: [{ label: 'Unità', price: 37 }],
    stock: null,
  },
  {
    name: 'CLOMIPHENE CITRATE',
    emoji: '🔄',
    category: 'pct',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'pct'],
    variants: [{ label: 'Unità', price: 35 }],
    stock: null,
  },
  {
    name: 'EXEMESTANE',
    emoji: '🔄',
    category: 'pct',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'pct'],
    variants: [{ label: 'Unità', price: 74 }],
    stock: null,
  },
  {
    name: 'LETROZOLE',
    emoji: '🔄',
    category: 'pct',
    origin: 'Astera Labs',
    tags: ['astera-labs', 'pct'],
    variants: [{ label: 'Unità', price: 17 }],
    stock: null,
  },

  // --- POST CYCLE THERAPY (PCT) — Biaxol ---
  {
    name: 'PCT IN CAPSULES',
    emoji: '🔄',
    category: 'pct',
    origin: 'Biaxol',
    tags: ['biaxol', 'pct'],
    variants: [{ label: 'Unità', price: 74 }],
    stock: 0,
  },
  {
    name: 'CYCLE SUPPORT',
    emoji: '🔄',
    category: 'pct',
    origin: 'Biaxol',
    tags: ['biaxol', 'pct'],
    variants: [{ label: 'Unità', price: 44 }],
    stock: 0,
  },
]
